// <auto-generated />
using System;
using GICTechTest.Model.DBModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GICTechTest.Model.Migrations
{
    [DbContext(typeof(GICTechTest_Context))]
    [Migration("20190727024356_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GICTechTest.Model.DBModels.Actuals", b =>
                {
                    b.Property<int>("State");

                    b.Property<double?>("ActualHouseholds");

                    b.Property<double?>("ActualPopulation");

                    b.HasKey("State");

                    b.ToTable("Actuals");
                });

            modelBuilder.Entity("GICTechTest.Model.DBModels.Estimates", b =>
                {
                    b.Property<int>("State");

                    b.Property<int>("Districts");

                    b.Property<double?>("EstimatesHouseholds");

                    b.Property<double?>("EstimatesPopulation");

                    b.HasKey("State", "Districts");

                    b.ToTable("Estimates");
                });
#pragma warning restore 612, 618
        }
    }
}
